=== Serheev/SpringShellDoc/in/usersWithMeals.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://serheev.com"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://serheev.com" elementFormDefault="qualified">

  <xs:element name="UsersWithMeals">
    <xs:complexType>
      <xs:all>
        <xs:element name="Users">
          <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
              <xs:element ref="User"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:element name="User">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Meals" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="email" use="required"/>
      <xs:attribute type="xs:string" name="password" use="required"/>
      <xs:attribute type="xs:int" name="caloriesPerDay" use="required"/>
      <xs:attribute type="xs:dateTime" name="registered" use="required"/>
      <xs:attribute type="xs:boolean" name="enabled" use="required"/>
      <xs:attribute type="roles" name="roles"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="roles">
    <xs:list itemType="roleTypes"/>
  </xs:simpleType>

  <xs:simpleType name="roleTypes">
    <xs:restriction base="xs:string">
      <xs:enumeration value="admin"/>
      <xs:enumeration value="user"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="Meals">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Meal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Meal">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:int" name="calories" use="required"/>
          <xs:attribute type="xs:dateTime" name="dateTime" use="required"/>
          <xs:attribute type="xs:boolean" name="excess"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Serheev/SpringShellDoc/in/badXmlFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<UsersWithMeals xmlns="http://serheev.com"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://serheev.com usersWithMeals.xsd">
    <Users>
        <User enabled="true" caloriesPerDay="2005" name="User"
              password="password" registered="2024-01-01T13:00:00" roles="user">
            <Meals>
                <Meal calories="500" dateTime="2024-01-30T10:00:00">Breakfast</Meal>
                <Meal calories="1000" dateTime="2024-01-30T13:00:00">Lunch</Meal>
                <Meal calories="500" dateTime="2024-01-30T20:00:00">Dinner</Meal>
                <Meal calories="100" dateTime="2024-01-31T00:00:00">Food to the limit</Meal>
                <Meal calories="500" dateTime="2024-01-31T10:00:00" foo="bar">Breakfast</Meal>
                <Meal calories="1000" dateTime="2024-01-30T13:00:00">Lunch</Meal>
                <Meal calories="510" dateTime="2024-01-30T20:00:00">Dinner</Meal>
            </Meals>
        </User>
        <User email="admin@serheev.com" caloriesPerDay="1900" name="Admin"
              password="admin" registered="2024-01-01T13:00:00" roles="admin user">
            <Meals>
                <Meal calories="510" dateTime="2024-01-30T14:00:00">Admin Lunch</Meal>
                <Meal calories="730" dateTime="2024-01-30T21:00:00">Admin Dinner</Meal>
            </Meals>
        </User>
        <User enabled="false" email="guest@serheev.com" caloriesPerDay="2000" name="Guest"
              password="guest" registered="2024-01-01T13:00:00">
        </User>
    </Users>
</UsersWithMeals>
